short_description: >
  A benchmark to measure schedule latency.

homepage: https://git.kernel.org/pub/scm/linux/kernel/git/mason/schbench.git

parameters:
  message_threads: number of message threads
  worker_threads: number of workers per message thread
  runtime: seconds to run before exiting
  iterations: number of iterations

results:
  schbench.wakeup_latency_50%_us
  schbench.wakeup_latency_50%_us_stddev%
  schbench.wakeup_latency_90%_us
  schbench.wakeup_latency_90%_us_stddev%
  schbench.wakeup_latency_99%_us
  schbench.wakeup_latency_99%_us_stddev%
  schbench.wakeup_latency_99.9%_us
  schbench.wakeup_latency_min_us
  schbench.wakeup_latency_max_us
  schbench.wakeup_latency_max_us_stddev%
  schbench.wakeup_end_latency_50%_us_max
  schbench.wakeup_end_latency_50%_us_stddev%
  schbench.wakeup_end_latency_90%_us_max
  schbench.wakeup_end_latency_90%_us_stddev%
  schbench.wakeup_end_latency_99%_us_max
  schbench.wakeup_end_latency_99%_us_stddev%
  schbench.wakeup_end_latency_99.9%_us_max
  schbench.request_latency_50%_us
  schbench.request_latency_50%_us_stddev%
  schbench.request_latency_90%_us
  schbench.request_latency_90%_us_stddev%
  schbench.request_latency_99%_us
  schbench.request_latency_99%_us_stddev%
  schbench.request_latency_99.9%_us
  schbench.request_latency_99.9%_us_stddev%
  schbench.request_latency_min_us
  schbench.request_latency_min_us_stddev%
  schbench.request_latency_max_us
  schbench.request_latency_max_us_stddev%
  schbench.request_end_latency_50%_us_max
  schbench.request_end_latency_50%_us_stddev%
  schbench.request_end_latency_90%_us_max
  schbench.request_end_latency_90%_us_stddev%
  schbench.request_end_latency_99%_us_max
  schbench.request_end_latency_99%_us_stddev%
  schbench.request_end_latency_99.9%_us_max
  schbench.request_end_latency_99.9%_us_stddev%
